{{- $name := include "data-source-hub-api.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "data-source-hub-api.name" . }}
    chart: {{ template "data-source-hub-api.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  foundationallm-app-configuration-uri: {{ .Values.appConfig.uri }}
