{{- $name := include "datapipeline-frontendworker.fullname" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: "secret-{{ $name }}"
  labels:
    app: {{ template "datapipeline-frontendworker.name" . }}
    chart: {{ template "datapipeline-frontendworker.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  FoundationaLLM_AppConfig_ConnectionString: {{ .Values.appConfig.connectionString | b64enc }}
