name: Data Pipeline Backend Worker Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  release_docker_image:
    name: Release Docker Image
    uses: ./.github/workflows/release-docker-image.yml
    with:
      image: datapipeline-backendworker
      context: ./src
      dockerfile: ./src/dotnet/DataPipelineBackendWorker/Dockerfile
