{{- $name := include "datapipeline-backendworker.fullname" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "datapipeline-backendworker.name" . }}
    chart: {{ template "datapipeline-backendworker.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data: 
  AZURE_CLIENT_ID: {{ .Values.azureWorkloadIdentity.dataPipelineBackendWorkerClientId }}
